# Generated by Django 2.1.8 on 2019-05-17 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicatednewspage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publish date'),
            preserve_default=False,
        ),
    ]
