# Generated by Django 2.1.8 on 2019-05-16 10:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0002_richtextpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtextpage',
            name='quite_rich_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A rich text field with few very formatting options'),
        ),
        migrations.AlterField(
            model_name='richtextpage',
            name='very_rich_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A rich text field with many formatting options'),
        ),
    ]
