# Generated by Django 2.1.8 on 2019-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='source_link',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
