# Generated by Django 2.1.8 on 2019-05-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190509_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspagenewscategory',
            old_name='news_category',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='newspagenewscategory',
            unique_together={('page', 'category')},
        ),
    ]
