# Generated by Django 2.1.8 on 2019-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190509_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='key_phrases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspage',
            name='sentiment',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
    ]
