# Generated by Django 2.1.8 on 2019-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190509_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
