# Generated by Django 2.1.8 on 2019-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsindexpage'),
        ('news', '0007_newspage_legacy_id'),
    ]

    operations = [
    ]
