# Generated by Django 2.1.8 on 2019-05-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_thanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='syndicate',
        ),
    ]
