# Generated by Django 2.1.11 on 2020-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_constituentformpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituentformpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
