# Generated by Django 2.1.11 on 2020-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_add_form_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituentformpage',
            name='action_text',
            field=models.CharField(blank=True, help_text='Form action text. Defaults to "Submit"', max_length=32),
        ),
    ]
