# Generated by Django 2.1.8 on 2019-04-25 06:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('podcasts', '0003_remove_show_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeEnclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.FileField(upload_to='media')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('bitrate', models.PositiveIntegerField(null=True)),
                ('sample_rate', models.PositiveIntegerField(null=True)),
                ('channel', models.CharField(blank=True, choices=[('mono', 'Mono'), ('stereo', 'Stereo')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=20)),
                ('collection', models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('episode', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosures', to='podcasts.Episode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
