# Generated by Django 2.1.8 on 2019-04-25 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_episodeenclosure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodeenclosure',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='episodeenclosure',
            name='file_size',
        ),
        migrations.AddField(
            model_name='episodeenclosure',
            name='channels',
            field=models.PositiveSmallIntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='episodeenclosure',
            name='bitrate',
            field=models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='episodeenclosure',
            name='mime_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='episodeenclosure',
            name='sample_rate',
            field=models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
