# Generated by Django 2.1.8 on 2019-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20190430_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommedia',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
