# Generated by Django 2.1.8 on 2019-05-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20190501_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommedia',
            name='is_transcribed',
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
