# Generated by Django 2.1.8 on 2019-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_custommedia_is_transcribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='share_with_member_stations',
            field=models.BooleanField(default=False, help_text='Allow this content to be published by NPR member stations'),
        ),
        migrations.AddField(
            model_name='episode',
            name='share_with_npr',
            field=models.BooleanField(default=False, help_text='Allow this content to be published on NPR.org'),
        ),
    ]
