# Generated by Django 2.1.8 on 2019-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20190519_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='share_with_member_stations',
            field=models.BooleanField(default=False, help_text='Allow this content to be published by NPR member stations', verbose_name='Share with NPR member stations'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='share_with_npr',
            field=models.BooleanField(default=False, help_text='Allow this content to be published on NPR.org', verbose_name='Share with NPR.org'),
        ),
    ]
