# Generated by Django 2.1.8 on 2019-05-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_auto_20190519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeenclosure',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='podcasts.CustomMedia'),
        ),
    ]
